fragment CollectionBaseFragment on Collection {
  id
  name
  slug
  description
  featuredAsset {
    id
    preview
  }
}

fragment CollectionMenuFragment on Collection {
  id
  name
  slug
  parentId
  featuredAsset {
    id
    preview
  }
  children {
    id
    name
    slug
    featuredAsset {
      id
      preview
    }
  }
}
