query GetMenuCollections {
  collections(options: { topLevelOnly: true }) {
    items {
      ...CollectionMenuFragment
    }
  }
}

query GetCollection($slug: String!) {
  collection(slug: $slug) {
    ...CollectionBaseFragment
  }
}

query GetCollectionProducts($slug: String!, $skip: Int, $take: Int) {
  search(
    input: {
      collectionSlug: $slug
      groupByProduct: true
      skip: $skip
      take: $take
    }
  ) {
    totalItems
    items {
      ...ProductSearchFragment
    }
  }
}
