query GetProduct($id: ID!) {
  product(id: $id) {
    ...ProductBaseFragment
  }
}

query GetProducts($take: Int = 12, $skip: Int = 0) {
  products(options: { take: $take, skip: $skip }) {
    items {
      ...ProductBaseFragment
    }
    totalItems
  }
}

query GetProductDetail($slug: String!) {
  product(slug: $slug) {
    ...ProductDetailFragment
  }
}
