
query GetAccesses($options: DigitalAccessListOptions) {
    activeCustomer {
        digitalAccesses(options: $options) {
            items {
                id
                createdAt
                updatedAt
                productId
                product {
                    id
                    name
                    slug
                }
                accessStartDate
                accessEndDate
                remainingVisits
                totalVisits
                orderId
                isActive
                totalDurationDays
                daysRemaining
            }
            totalItems
        }
    }

}

