mutation LKUpdateCustomer($input: UpdateCustomerInput!) {
    updateCustomer(input: $input) {
        ...CustomerDetail
        customFields {
            socialList {
                profile
                socialType
            }
        }
    }
}